---
- name: Create a new user on app
  hosts: all
  become: true
  tasks:
    - name : Creating new user
      user :
        name : "{{ sname }}"
        password: playbookuser
        comment : "{{ sfull }}"
        shell : /bin/bash
        home : /home/{{ sname }}    
        group: "{{ sname }}"
